### PR TITLE
Make time slot based views also display rogue reservations

### PR DESCRIPTION
**Pull request by tituomin**
Previously, reservations which didn't conform to
the time slot divisions didn't get displayed at all.

See url resources/avkl2qpsfuua?begin=2017-08-22 for an example

### CODE REVIEW

**Comment by jussiarpalahti** [comment]
I don't get what visual stuff does from looking at the changes, but probably it works.

**Comment by tituomin** [comment]
I made some test so that the codecov warning above has also been fixed.

**Review by jussiarpalahti — APPROVED** [review]
I see no obvious problems (though my understanding here is of limited sort).

**Review by Rikuoja — APPROVED** [review]
Seems like it should work.

**Pull request merged**
