### PR TITLE
Compatibility downgrade url-loader

### PR DESCRIPTION
**Pull request by terotik**

### CODE REVIEW

**Review by jussiarpalahti — APPROVED** [review]
Easy way out :)

**Comment by jussiarpalahti** [comment]
@juyrjola I think this can be merged even though Travis with node 6.5.11 has some odd complaints
on our slightly older node tests pass

**Comment by hukka** [comment]
Hmh. 10 minutes of looking at the failing tests didn't give any insights. I'll try rerunning the tests… Not sure if I'm hoping they'll pass or fail again.

**Comment by hukka** [comment]
Passed. So we have transient build failures in CI. Great.

**Review by hukka — APPROVED** [review]

**Pull request closed without merging**
